fixtures:
  repositories:
    apt:
      repo: "https://github.com/puppetlabs/puppetlabs-apt"
      ref: master
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    altlib: "https://github.com/opentable/puppet-altlib.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile"
    puppetlabs_yum: "https://github.com/stahnma/puppet-module-puppetlabs_yum"
  symlinks:
    puppetversion: "#{source_dir}"
