---

driver:
  name: vagrant
  timeout_in_seconds: 3600

provisioner:
  name: puppet_apply
  modules_path: modules
  hiera_data_path: hiera
  sudo: false
  puppet_version: 3.4.2
  puppet_platform: windows

platforms:
  - name: windows-2008-serverstandard-x64
    driver_plugin: vagrant
    driver_config:
      box : win-2008-standard-amd64-nocm
      box_url : "/Users/liamjbennett/Dev/public/packer-images/windows/templates/windows-2008R2-serverstandard-amd64/windows-2008R2-serverstandard-amd64_virtualbox.box"
      username: Administrator
      guest: :windows

suites:
  - name: windows_default
    manifest: site.pp
